// User
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

// Playlist
export const GET_USER_PLAYLIST = "GET_USER_PLAYLIST";
export const REMOVE_TRACK_FROM_PLAYLIST = "REMOVE_TRACK_FROM_PLAYLIST";
export const GET_PLAYLIST_TRACKS = "GET_PLAYLIST_TRACKS";
export const GET_PLAYLIST_IMAGE = "GET_PLAYLIST_IMAGE";
export const GET_PLAYLIST_BY_ID = "GET_PLAYLIST_BY_ID";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const GET_CURRENT_USER_PLAYLIST = "GET_CURRENT_USER_PLAYLIST";
export const ADD_TRACK_TO_PLAYLIST = "ADD_TRACK_TO_PLAYLIST";

// Tracks

export const GET_TRACK = "GET_TRACK";
export const GET_USER_TRACK = "GET_USER_TRACK";
export const REMOVE_USER_TRACK = "REMOVE_USER_TRACK";
export const SAVE_TRACK_FOR_USER = "SAVE_TRACK_FOR_USER";

// Shows

export const SAVE_SHOWS_FOR_USER = "SAVE_SHOWS_FOR_USER";
export const REMOVE_USER_SHOWS = "REMOVE_USER_SHOWS";
export const GET_USER_SHOWS = "GET_USER_SHOWS";
export const GET_SHOW_EPISODES = "GET_SHOW_EPISODES";
export const GET_SHOW = "GET_SHOW";

// Player
export const START_OR_RESUME_PLAYBACK = "START_OR_RESUME_PLAYBACK";
export const GET_USER_CURRENTLY_PLAYING = "GET_USER_CURRENTLY_PLAYING";
export const GET_USER_CURRENTLY_PLAYBACK = "GET_USER_CURRENTLY_PLAYBACK";
export const PAUSE_PLAYBACK = "PAUSE_PLAYBACK";
export const SKIP_PLAYBACK_NEXT = "SKIP_PLAYBACK_NEXT";
export const SKIP_PLAYBACK_PREVIOUS = "SKIP_PLAYBACK_PREVIOUS";
export const SET_REPEAT_MODE = "SET_REPEAT_MODE";
export const SET_VOLUME = "SET_VOLUME";
export const GET_USER_RECENTLY_PLAYED_TRACK = "GET_USER_RECENTLY_PLAYED_TRACK";
export const ADD_ITEM_TO_QUEUE = "ADD_ITEM_TO_QUEUE";

// Personal
export const GET_USER_TOP_ARTIST = "GET_USER_TOP_ARTIST";
export const GET_USER_TOP_TRACKS = "GET_USER_TOP_TRACKS";

// Follow
export const FOLLOW_PLAYLIST = "FOLLOW_PLAYLIST";
export const UNFOLLOW_PLAYLIST = "UNFOLLOW_PLAYLIST";
export const GET_USER_FOLLOWED_ARTISTS = "GET_USER_FOLLOWED_ARTISTS";
export const FOLLOW_ARTIST_OR_USER = "FOLLOW_ARTIST_OR_USER";
export const UNFOLLOW_ARTIST_OR_USER = "UNFOLLOW_ARTIST_OR_USER";

// Browse
export const GET_NEW_RELEASES = "GET_NEW_RELEASES";
export const GET_ALL_FEATURED = "GET_ALL_FEATURED";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const GET_RECOMMENDATION_GENRES = "GET_RECOMMENDATION_GENRES";

// Albums

export const GET_USER_ALBUMS = "GET_USER_ALBUMS";
export const SAVE_ALBUMS = "SAVE_ALBUMS";
export const REMOVE_ALBUM = "REMOVE_ALBUM";

// Search
export const SEARCH = "SEARCH";
